### ISSUE TITLE
No discovery for Ranges / Arrays

### ISSUE THREAD

**Issue by lukassausen** [elbowz/ha-homie#6]
Hi elbowz,

first off all, many thanks for publishing this project! I never thought I would be able to eventually integrate my homie devices into HA (without manual config).

I had a look at the your readme but couldn't find any information on which Version of homie convention this plugin can handle. If you are covering 3.0.0 / 3.0.1, did you already implement [Arrays](https://homieiot.github.io/specification/spec-core-v3_0_1/#arrays)? 

It seems that roperties initialized via the [range feature of the homie-esp8266 framework ](https://github.com/homieiot/homie-esp8266/blob/develop/examples/LedStrip/LedStrip.ino) are currently not visible via your HA integration.

Regards,
Lukas

**Comment by elbowz** [comment]
Hi @lukassausen,

 sorry for the delayed answer but I was positive and quite busy  (as usually).

In truth I have developed the component but not still using in "production", so I don't know if I can directly follow the development (aka PR are really appreciated :).

> I had a look at the your readme but couldn't find any information on which Version of homie convention this plugin can handle. If you are covering 3.0.0 / 3.0.1, did you already implement [Arrays](https://homieiot.github.io/specification/spec-core-v3_0_1/#arrays)?

I have a couple of homie devices with the esp8266 used for bring ahead the development of my HA custom component. So I have not implemented the full homie 3.0.1 convention, but a subpart that you can figure out by README, or directly using it.

Unfortunately, Array is not implemented right now, simply because I don't have any homie device that use it. If I have well understood, Array is implemented by HomieRange in homie-esp8266, right? Something like the RGB stripes led?

Questions: 
1. Are you already use Homie array in HA (with MQTT custom/manual config)? 
2. If yes, what kind of devices are...and more important which [Entity](https://developers.home-assistant.io/docs/core/entity) do you use?

Ciao!

p.s. sorry for my english

**Comment by lukassausen** [comment]
Hi @elbowz,

apologies for replying so late from my end as well. (Same here with corona and a lot of other stuff going on).

I already thought about trying to do a fork and start developing this on my own. Unfortunately, I am quite an amateur when it comes to coding and I know very little about object oriented prorgramming or HA design patterns. :grimacing: 

Nevertheless, I can fill you in on the details of my setup:

> Array is implemented by HomieRange in homie-esp8266, right? Something like the RGB stripes led?

Correct, you can easily create a "range Node" via parameters 4 to 6 in the HomieNode class. I also used the RGB stripe example as a starting point for my ESP8266 project.


> Are you already use Homie array in HA (with MQTT custom/manual config)?
 
Right now I integrated Homie Arrays via manual setup of each property in the HA config yaml. See below example:

```yaml
switch:
  - platform: mqtt
    name: "Outlet 1"
    state_topic: "homie/bridge-node/outlet_1/outlet"
    command_topic: "homie/bridge-node/outlet_1/outlet/set"
    <<: &default
      payload_on: "true"
      payload_off: "false"
      state_on: "true"
      state_off: "false"
      device_class: "outlet"
  - platform: mqtt
    name: "Outlet 2"
    state_topic: "homie/bridge-node/outlet_2/outlet"
    command_topic: "homie/bridge-node/outlet_2/outlet/set"
    <<: *default
  - platform: mqtt
    name: "Outlet 3"
    state_topic: "homie/bridge-node/outlet_3/outlet"
    command_topic: "homie/bridge-node/outlet_3/outlet/set"
    <<: *default
  - platform: mqtt
    name: "Outlet 4"
    state_topic: "homie/bridge-node/outlet_4/outlet"
    command_topic: "homie/bridge-node/outlet_4/outlet/set"
    <<: *default
```

> If yes, what kind of devices are...and more important which [Entity](https://developers.home-assistant.io/docs/core/entity) do you use?

I currently have two devices in place:
1. MQTT to 433 MHz bridge (based on on ESP8266) - using 4 switch entities here.
2. Automated garden watering system (based on ESP32) - using 4 sensor entities (soil humidity sensors) + 4 switch entities (valves)

Hope this information helps.

PS: No need to worry about your englisch skills! :slightly_smiling_face:
